export const spaceConditionKeywords = [
  { en: 'Hardwood Companion', ko: '목재와 잘 어울리는' },
  { en: 'High Humidity Thrivers', ko: '고습도 생존자' },
  { en: 'Low Light Tolerant', ko: '저조도 내성' },
  { en: 'Pet-Friendly', ko: '반려동물 친화적' },
  { en: 'Air-Purifying', ko: '공기 정화' },
  { en: 'Drought-Resistant', ko: '가뭄 저항성' },
  { en: 'Small Spaces', ko: '작은 공간' },
  { en: 'Large Spaces', ko: '큰 공간' },
  { en: 'Minimalist Decor', ko: '미니멀리스트 장식' },
  { en: 'Tropical Vibes', ko: '열대 분위기' },
  { en: 'Desk Plants', ko: '책상용 식물' },
  { en: 'Hanging Varieties', ko: '매달린 종류' },
  { en: 'Feng Shui Plants', ko: '풍수 식물' },
  { en: 'Colorful Foliage', ko: '다채로운 잎' },
  { en: 'Fragrant', ko: '향기로운' },
];

export const voiceToneKeywords = [
  { en: 'Soothing', ko: '진정시키는' },
  { en: 'Energetic', ko: '에너지 넘치는' },
  { en: 'Professional', ko: '전문적인' },
  { en: 'Bold', ko: '대담한' },
  { en: 'Sophisticated', ko: '세련된' },
  { en: 'Trendy', ko: '트렌디한' },
  { en: 'Welcoming', ko: '환영하는' },
  { en: 'Classic', ko: '클래식한' },
  { en: 'Adaptable', ko: '적응력 있는' },
  { en: 'Minimalist', ko: '미니멀리스트' },
  { en: 'Elegant', ko: '우아한' },
  { en: 'Playful', ko: '장난스러운' },
  { en: 'Architectural', ko: '건축적인' },
  { en: 'Confident', ko: '자신감 있는' },
  { en: 'Artistic', ko: '예술적인' },
  { en: 'Chic', ko: '시크한' },
  { en: 'Friendly', ko: '친근한' },
];

export const themeKeywords = [
  { en: 'Spring Renewal', ko: '봄맞이' },
  { en: 'Summer Vibrance', ko: '여름의 생기' },
  { en: 'Autumn Harvest', ko: '가을 수확기' },
  { en: 'Winter Solace', ko: '겨울 위로' },
  { en: 'Christmas Cheer', ko: '크리스마스' },
  { en: 'New Year Fresh Start', ko: '새해맞이' },
  { en: "Valentine's Romance", ko: '발렌타인 낭만' },
  { en: 'Winter Wonderland', ko: '겨울동화' },
];
